variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

trigger: none

pr:
  branches:
    include:
      - master
  paths:
    include:
      - source/trx2junit/Extensions/TimeExtensions.cs
      - source/trx2junit/Extensions/Vector128Extensions.cs

stages:
  - stage: Build_Test
    jobs:
      - template: jobs/build_and_test_vectors.yml

  - stage: Code_Coverage
    dependsOn:
      - Build_Test
    jobs:
      - template: jobs/coverage.yml
