variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

#schedules:
#  - cron: "0 0 * * *"
#    displayName: "Daily midnight build"
#    branches:
#      include:
#        - master

stages:
  - stage: Build_Test
    jobs:
      - template: jobs/build_and_test.yml

  - stage: E2E_Tests
    dependsOn:
      - Build_Test
    jobs:
      - template: jobs/e2e_tests.yml

  - stage: Code_Coverage
    dependsOn:
      - Build_Test
    jobs:
      - template: jobs/coverage.yml

  - stage: Deploy
    dependsOn:
      - E2E_Tests      
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_nuget.yml
