jobs:
  - job: coverage_report_quality
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      # checkout is needed for file-references
      #- checkout: none

      - task: DownloadPipelineArtifact@2
        inputs:
          targetPath: './coverage'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'coverage/**/Cobertura.xml'
          pathToSources: $(System.DefaultWorkingDirectory)

      # extension from Marketplace https://marketplace.visualstudio.com/acquisition?itemName=mspremier.BuildQualityChecks
      - task: BuildQualityChecks@6
        displayName: 'Check build quality'
        inputs:
          checkCoverage: true
          coverageFailOption: 'build'
          coverageType: 'lines'
          allowCoverageVariance: true
          coverageVariance: '0.5'
          baseBranchRef: 'master'
